README.md: guessinggame.sh
	echo "# Guessing Game" > README.md
	echo "" >> README.md
	echo "Date and Time of Make: $(shell date)" >> README.md
	echo "" >> README.md
	echo "Number of Lines in guessinggame.sh: $(shell wc -l < guessinggame.sh)" >> README.md

.PHONY: clean
clean:
	rm -f README.md